services:
  - type: web
    name: clockdin-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://clockdin-backend.onrender.com

  - type: web
    name: clockdin-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        value: clockdinapp@gmail.com
      - key: EMAIL_PASS
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID 
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://clockdin-frontend.onrender.com
      - key: SERVER_URL
        value: https://clockdin-backend.onrender.com
    healthCheckPath: /health